#!/bin/zsh
cd /Users/johnhausman/source/immich || exit 1
mkdir -p assistant-agent-logs
export ASSISTANT_BRIDGE_SYNOLOGY_HOST="${ASSISTANT_BRIDGE_SYNOLOGY_HOST:-drhaus}"
export ASSISTANT_BRIDGE_SYNOLOGY_PORT="${ASSISTANT_BRIDGE_SYNOLOGY_PORT:-22222}"
export ASSISTANT_BRIDGE_SYNOLOGY_USER="${ASSISTANT_BRIDGE_SYNOLOGY_USER:-hausmanj}"
export ASSISTANT_BRIDGE_SYNOLOGY_ROOT="${ASSISTANT_BRIDGE_SYNOLOGY_ROOT:-/volume1}"
export ASSISTANT_BRIDGE_SYNOLOGY_DEFAULT_CWD="${ASSISTANT_BRIDGE_SYNOLOGY_DEFAULT_CWD:-/volume1}"
export ASSISTANT_BRIDGE_IMMICH_CONTAINER="${ASSISTANT_BRIDGE_IMMICH_CONTAINER:-immich_server}"
export ASSISTANT_BRIDGE_IMMICH_ROOT="${ASSISTANT_BRIDGE_IMMICH_ROOT:-/}"
export ASSISTANT_BRIDGE_IMMICH_DEFAULT_CWD="${ASSISTANT_BRIDGE_IMMICH_DEFAULT_CWD:-/usr/src/app}"
exec /opt/homebrew/bin/node tools/assistant-cli-bridge.mjs >> assistant-agent-logs/bridge.command.log 2>&1
